# Generated by Django 6.1.2 on 2026-10-09 22:00

from django.db import migrations, models
from django.utils.text import slugify


def latin_slugs(apps, schema_editor):
    # Freeze the transliteration here so future changes cannot alter this migration.
    translation = str.maketrans(dict(zip(
        "абвгдеёжзийклмнопрстуфхцчшщъыьэюя",
        ("a", "b", "v", "g", "d", "e", "yo", "zh", "z", "i", "y",
         "k", "l", "m", "n", "o", "p", "r", "s", "t", "u", "f",
         "h", "ts", "ch", "sh", "shch", "", "y", "", "e", "yu", "ya"),
        strict=True,
    )))
    Article = apps.get_model("articles", "Article")
    articles = Article.objects.using(schema_editor.connection.alias)
    for article in articles.order_by("pk").iterator():
        if article.slug and article.slug.isascii():
            continue
        base = slugify((article.slug or article.title).lower().translate(translation)) or "article"
        slug = base[:255].rstrip("-_")
        number = 2
        while articles.exclude(pk=article.pk).filter(slug=slug).exists():
            suffix = f"-{number}"
            slug = base[:255 - len(suffix)].rstrip("-_") + suffix
            number += 1
        articles.filter(pk=article.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_slug'),
    ]

    operations = [
        migrations.RunPython(latin_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Часть URL после /articles/. Латинские буквы, цифры, дефисы и подчёркивания. Если адрес не заполнен, он будет сгенерирован автоматически из заголовка латиницей при сохранении.', max_length=255, unique=True, verbose_name='Адрес статьи'),
        ),
    ]
