# Generated by Django 6.1.2 on 2026-10-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Лотошинский церковный округ', max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Пока не используется: содержимое главной задано в шаблоне.', verbose_name='Вступительный текст')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO-заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO-описание')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='home_page_singleton')],
            },
        ),
    ]
