# Generated by Django 6.1.2 on 2026-10-11 00:00

import document_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to=document_library.models.document_upload_path, verbose_name='Документ')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Имя файла')),
                ('file_format', models.CharField(editable=False, max_length=8, verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
