# Generated by Django 6.1.2 on 2026-10-10 23:36

import django.core.validators
from django.db import migrations, models


def create_settings(apps, schema_editor):
    SiteSettings = apps.get_model("site_settings", "SiteSettings")
    SiteSettings.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_upload_size_mb', models.PositiveIntegerField(default=10, help_text='Лимит одного файла любого типа: изображения, документа и других файлов.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный размер файла для загрузки, МБ')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='site_settings_singleton')],
            },
        ),
        migrations.RunPython(create_settings, migrations.RunPython.noop),
    ]
