# Generated by Django 6.1.2 on 2026-10-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_image_webp',
            field=models.BooleanField(default=True, verbose_name='WebP (.webp)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_file_doc',
            field=models.BooleanField(default=True, verbose_name='DOC (.doc)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_file_docx',
            field=models.BooleanField(default=True, verbose_name='DOCX (.docx)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_file_odt',
            field=models.BooleanField(default=True, verbose_name='ODT (.odt)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_file_pdf',
            field=models.BooleanField(default=True, verbose_name='PDF (.pdf)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_file_rtf',
            field=models.BooleanField(default=True, verbose_name='RTF (.rtf)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_image_jpeg',
            field=models.BooleanField(default=True, verbose_name='JPEG (.jpg, .jpeg)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_image_png',
            field=models.BooleanField(default=True, verbose_name='PNG (.png)'),
        ),
    ]
