# Generated by Django 6.1.2 on 2026-10-10 23:30

import django.core.validators
from django.db import migrations, models


def create_settings(apps, schema_editor):
    ImageSettings = apps.get_model("media_library", "ImageSettings")
    ImageSettings.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('max_upload_size_mb', models.PositiveIntegerField(default=10, help_text='Общий лимит для новых файлов в редакторе и медиабиблиотеке.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный размер загружаемого файла, МБ')),
                ('gallery_preview_width', models.PositiveSmallIntegerField(default=400, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина превью, px')),
                ('gallery_preview_height', models.PositiveSmallIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота превью, px')),
                ('gallery_full_width', models.PositiveSmallIntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина полного изображения, px')),
                ('gallery_full_height', models.PositiveSmallIntegerField(default=1536, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота полного изображения, px')),
                ('gallery_portrait_preview_width', models.PositiveSmallIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина превью, px')),
                ('gallery_portrait_preview_height', models.PositiveSmallIntegerField(default=400, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота превью, px')),
                ('gallery_portrait_full_width', models.PositiveSmallIntegerField(default=1536, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина полного изображения, px')),
                ('gallery_portrait_full_height', models.PositiveSmallIntegerField(default=2048, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота полного изображения, px')),
                ('article_preview_width', models.PositiveSmallIntegerField(default=320, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина превью, px')),
                ('article_preview_height', models.PositiveSmallIntegerField(default=240, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота превью, px')),
                ('article_full_width', models.PositiveSmallIntegerField(default=1280, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина полного изображения, px')),
                ('article_full_height', models.PositiveSmallIntegerField(default=960, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота полного изображения, px')),
                ('article_portrait_preview_width', models.PositiveSmallIntegerField(default=240, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина превью, px')),
                ('article_portrait_preview_height', models.PositiveSmallIntegerField(default=360, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота превью, px')),
                ('article_portrait_full_width', models.PositiveSmallIntegerField(default=960, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина полного изображения, px')),
                ('article_portrait_full_height', models.PositiveSmallIntegerField(default=1440, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота полного изображения, px')),
            ],
            options={
                'verbose_name': 'Настройки изображений',
                'verbose_name_plural': 'Настройки изображений',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='image_settings_singleton')],
            },
        ),
        migrations.RunPython(create_settings, migrations.RunPython.noop),
    ]
