# Generated by Django 6.1.2 on 2026-10-10 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_imagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesettings',
            name='max_upload_size_mb',
        ),
        migrations.AddField(
            model_name='imagesettings',
            name='max_image_height',
            field=models.PositiveSmallIntegerField(default=2560, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Максимальная высота, px'),
        ),
        migrations.AddField(
            model_name='imagesettings',
            name='max_image_width',
            field=models.PositiveSmallIntegerField(default=2560, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Максимальная ширина, px'),
        ),
    ]
