# Generated by Django 6.1.2 on 2026-10-10 23:49

import django.db.models.deletion
import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_remove_imagesettings_max_upload_size_mb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('source_name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('article_preview', 'Статья — превью'), ('article_full', 'Статья — полная версия')], max_length=32)),
                ('max_width', models.PositiveSmallIntegerField()),
                ('max_height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('file', models.ImageField(upload_to=media_library.models.image_upload_path)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='media_library.image')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('image', 'source_name', 'kind', 'max_width', 'max_height'), name='unique_image_rendition')],
            },
        ),
    ]
